INSERT INTO ships (name, movie) VALUES ('Death Star', 'Star Wars');
INSERT INTO ships (name, movie) VALUES ('Millennium Falcon', 'Star Wars');
INSERT INTO ships (name, movie) VALUES ('USS Enterprise', 'Star Trek');
INSERT INTO ships (name, movie) VALUES ('Serenity', 'Firefly');
INSERT INTO ships (name, movie) VALUES ('TARDIS', 'Doctor Who');
INSERT INTO ships (name, movie) VALUES ('Battlestar Galactica', 'Battlestar Galactica');
INSERT INTO ships (name, movie) VALUES ('Nostromo', 'Alien');
INSERT INTO ships (name, movie) VALUES ('Discovery One', '2001: A Space Odyssey');
INSERT INTO ships (name, movie) VALUES ('Nebuchadnezzar', 'The Matrix');
INSERT INTO ships (name, movie) VALUES ('Heart of Gold', 'The Hitchhiker''s Guide to the Galaxy');
INSERT INTO ships (name, movie) VALUES ('Event Horizon', 'Event Horizon');
INSERT INTO ships (name, movie) VALUES ('Normandy SR-2', 'Mass Effect');
INSERT INTO ships (name, movie) VALUES ('Moya', 'Farscape');
INSERT INTO ships (name, movie) VALUES ('Voyager', 'Star Trek: Voyager');
INSERT INTO ships (name, movie) VALUES ('Andromeda Ascendant', 'Andromeda');
INSERT INTO ships (name, movie) VALUES ('Star Destroyer', 'Star Wars');
INSERT INTO ships (name, movie) VALUES ('X-Wing', 'Star Wars');
INSERT INTO ships (name, movie) VALUES ('TIE Fighter', 'Star Wars');
INSERT INTO ships (name, movie) VALUES ('Slave 1', 'Star Wars');
INSERT INTO ships (name, movie) VALUES ('Prometheus', 'Stargate SG-1');
INSERT INTO ships (name, movie) VALUES ('Daedalus', 'Stargate Atlantis');
INSERT INTO ships (name, movie) VALUES ('Destiny', 'Stargate Universe');
INSERT INTO ships (name, movie) VALUES ('Raza', 'Dark Matter');
INSERT INTO ships (name, movie) VALUES ('Rocinante', 'The Expanse');
INSERT INTO ships (name, movie) VALUES ('Sulaco', 'Aliens');